# Generated by Django 5.0.2 on 2024-02-13 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('response', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valentine_app.sender')),
            ],
        ),
    ]
